update

diff --git a/main b/main
--- a/main
+++ b/main
@@ -11,3 +11,18 @@ module load singularity 2> /dev/null
 echo "converting aparc+aseg file"
 
 time singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./convertfiles.sh"
+
+echo "making surfaces"
+
+singularity exec -e docker://brainlife/pythonvtk ./main.py
+
+count=$(ls surfaces/* | wc -l)
+
+if [ "$count" == 24 ] 
+then
+	echo 0 > finished
+else
+	echo "files missing"
+	echo 1 > finished
+	exit 1
+fi
